var GAME_LEVELS = [
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "     xx   xxx xxxxx    x  x  xxx x    x    xxxxx  xx     x       =       x xxx xx    x   xx                       ",
   "    xvvx  x     x      x x   x    x  x       x   xvvx     x      x      x   x  x x   x   xx                       ",
   "    x     xxx   x      xx    xxx   xx        x   x  x      x    x x    x    x  x  x  x   xx         xyyyy         ",
   "    x  xx x     x      x x   x     xx        x   x  x       x  x   x  x     x  x   x x             xxxxxyy        ",
   "     xxx  xxx   x      x  x  xxx   xx        x    xx         xx     xx     xxx x    xx   xx       xxxxxxxyy       ",
   "                                                                                                 xxxxyyxxxyy      ",
   "                                                                                                xxxxxxyyxxxyy     ",
   "                                        z                                 o                    xxxxxxxxyyxxxyy    ",
   "                                                                                              xxxxxxxxxxyyxxxyy   ",
   "                o                    xxxxxxx                                                 xxxxxxxxxxyyxxxxxyy  ",
   "                                       o                                                        k xxxxyyxxxxxxxyy ",
   "   @                  xwx                                                                         xxxyyxxxxxxxxxyy",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyyxxxxxxxxxxxyy",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["x                                                                                                        x",
   "x     k                                                                                                  x",
   "x                                                                                                        x",
   "x   xxxxx    xxxx                                                                                        x",
   "x                                                                         oooo                           x",
   "x                         o                                             ooo  ooo                         x",
   "x                       xxxx                                             oo  oo                          x",
   "x                                                                       xxxxxxxx                         x",
   "x              xxxxxx                            o                                                  o    x",
   "x                   v                                                                           =        x",
   "x o                                            xxxxxx                                          xxxxxx    x",
   "xxxxx                                                           xx|xxx                                   x",
   "x                            xxxxxxxxx                          xxxxxx                                xyyx",
   "x                                                                                     o               xyyx",
   "x                                                                                 xxxxxxxx            xyyx",
   "x   xxxxx                                     xxxxxxxxx                            v                  xyyx",
   "xyyy                                                                                                  xyyx",
   "xxxy                              xxxxx                                                               xxxx",
   "  xy         @                                                            xxx                            x",
   "  xy      xxxxxxxx        =             =      xxxxxx                                                    x",
   "  xy      x      x                        xxxxx     x                                                    x",
   "  xyyyyyyyx      x    xxxxxxxxxxxxxxxxxxxx          xxxxxx         o                     o            xwxx",
   "  xyyyyyyyx      x!!!!x                             x           xxxxxxx               xxxxxxxxx       xxxx",
   "  xyyyyyyyx      xxxxxx                             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "  xxxxxxxxx                                         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                          ",
   "                                                                                                          "],
  ["                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                         x    x  xx  x  x    xooooooooooooooox xxx xx    x   xx     xxxxx          ",
   "                                          x  x  x^^x x  x     xooooooxoooooox   x  x x   x   xx                    ",
   "yyyyyx                                     xx   x  x x  x      xoooox xoooox    x  x  x  x   xx                    ",
   "xxxyyxx                                    xx   x  x x kx       xoox   xoox     x  x   x x                         ",
   "xxyyxxxx                      xxxxx        xx    xx   xx         xx     xx     xxx x    xx   xx               xxxx ",
   "xxxyyxxxx                                                                                                          ",
   "xxxxyyxxxx                                                                                                         ",
   "xxxxxyyxxxx         xxxxxxxxxxx      xxxx                                                           xxxxx          ",
   "xxxxxxyyxxxx                                                                                                       ",
   "xxxxxxxyyxxxx                                                                                                      ",
   "xxxxxxyyxxxxxx                                                                        xxxxxxx                      ",
   "xxxxxyyxxxx                           xxxxxxxxx                                     xxxxxxxxxxx                    ",
   "xxxxyyxxxxx @                     xxxxxxxxxxxxxxxx                                xxxxxxxxxxxxxxxxx                ",
   "xxxyyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
